version: '3.7'

services:
  
  webserver:
    image: mariort/php-nginx:3.0
    volumes:
      - .:/www
    environment:
      - XDEBUG_CONFIG
    env_file:
      - .env
    ports:
      - "80:80"
    networks: 
      - default

networks:
  default:
    name: umbranet